[2024-08-27T17:00:00.961+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T17:00:00.967+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:00:00.968+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:00:00.991+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:00:00.992+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:00:01.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [queued]>
[2024-08-27T17:00:01.022+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [queued]>
[2024-08-27T17:00:01.023+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-27T17:00:01.034+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): calculate_exchange_rate_change> on 2024-08-27 16:00:00+00:00
[2024-08-27T17:00:01.039+0000] {standard_task_runner.py:57} INFO - Started process 415 to run task
[2024-08-27T17:00:01.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_dag', 'calculate_exchange_rate_change', 'scheduled__2024-08-27T16:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpvt8oli4n']
[2024-08-27T17:00:01.042+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask calculate_exchange_rate_change
[2024-08-27T17:00:01.052+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-27T17:00:01.078+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:00:01.078+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:00:01.080+0000] {task_command.py:410} INFO - Running <TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [running]> on host d374469d5083
[2024-08-27T17:00:01.088+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T17:00:01.144+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_dag' AIRFLOW_CTX_TASK_ID='calculate_exchange_rate_change' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T16:00:00+00:00'
[2024-08-27T17:00:01.150+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-27T17:00:01.158+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=currency_exchange_dag, task_id=calculate_exchange_rate_change, execution_date=20240827T160000, start_date=20240827T170001, end_date=20240827T170001
[2024-08-27T17:00:01.174+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-27T17:00:01.187+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T17:46:37.497+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:46:37.498+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:46:37.545+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:46:37.546+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:46:37.578+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T17:46:37.589+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [queued]>
[2024-08-27T17:46:37.598+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [queued]>
[2024-08-27T17:46:37.599+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-27T17:46:37.614+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): calculate_exchange_rate_change> on 2024-08-27 16:00:00+00:00
[2024-08-27T17:46:37.659+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2024-08-27T17:46:37.663+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_dag', 'calculate_exchange_rate_change', 'scheduled__2024-08-27T16:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpvlwe35ny']
[2024-08-27T17:46:37.664+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask calculate_exchange_rate_change
[2024-08-27T17:46:37.678+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-27T17:46:37.719+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T17:46:37.720+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T16:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T17:46:37.722+0000] {task_command.py:410} INFO - Running <TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T16:00:00+00:00 [running]> on host e4150be2da9f
[2024-08-27T17:46:37.735+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T17:46:37.824+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_dag' AIRFLOW_CTX_TASK_ID='calculate_exchange_rate_change' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T16:00:00+00:00'
[2024-08-27T17:46:37.914+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-27T17:46:37.932+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=currency_exchange_dag, task_id=calculate_exchange_rate_change, execution_date=20240827T160000, start_date=20240827T174637, end_date=20240827T174637
[2024-08-27T17:46:37.997+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-27T17:46:38.020+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
