[2024-08-26T19:01:10.851+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T19:01:10.857+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T19:01:10.857+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T19:01:10.884+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T19:01:10.885+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T19:01:10.921+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T18:00:00+00:00 [queued]>
[2024-08-26T19:01:10.929+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T18:00:00+00:00 [queued]>
[2024-08-26T19:01:10.930+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-26T19:01:10.942+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): calculate_exchange_rate_change> on 2024-08-26 18:00:00+00:00
[2024-08-26T19:01:10.946+0000] {standard_task_runner.py:57} INFO - Started process 455 to run task
[2024-08-26T19:01:10.948+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_dag', 'calculate_exchange_rate_change', 'scheduled__2024-08-26T18:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpg323ldgm']
[2024-08-26T19:01:10.949+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask calculate_exchange_rate_change
[2024-08-26T19:01:10.963+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T19:01:10.994+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T19:01:10.994+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T18:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T19:01:10.997+0000] {task_command.py:410} INFO - Running <TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T18:00:00+00:00 [running]> on host 5f8e3ab10fa1
[2024-08-26T19:01:11.010+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T19:01:11.121+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_dag' AIRFLOW_CTX_TASK_ID='calculate_exchange_rate_change' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T18:00:00+00:00'
[2024-08-26T19:01:11.130+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-26T19:01:11.140+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=currency_exchange_dag, task_id=calculate_exchange_rate_change, execution_date=20240826T180000, start_date=20240826T190110, end_date=20240826T190111
[2024-08-26T19:01:11.162+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-26T19:01:11.181+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
