[2024-08-26T22:00:00.618+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T22:00:00.623+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T22:00:00.624+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T22:00:00.649+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T22:00:00.650+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T22:00:00.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T21:00:00+00:00 [queued]>
[2024-08-26T22:00:00.689+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T21:00:00+00:00 [queued]>
[2024-08-26T22:00:00.690+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-26T22:00:00.701+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): calculate_exchange_rate_change> on 2024-08-26 21:00:00+00:00
[2024-08-26T22:00:00.704+0000] {standard_task_runner.py:57} INFO - Started process 1918 to run task
[2024-08-26T22:00:00.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_dag', 'calculate_exchange_rate_change', 'scheduled__2024-08-26T21:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpq40kx2ig']
[2024-08-26T22:00:00.708+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask calculate_exchange_rate_change
[2024-08-26T22:00:00.720+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T22:00:00.748+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-26T22:00:00.749+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-26T21:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-26T22:00:00.753+0000] {task_command.py:410} INFO - Running <TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-26T21:00:00+00:00 [running]> on host 5f8e3ab10fa1
[2024-08-26T22:00:00.764+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T22:00:00.822+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_dag' AIRFLOW_CTX_TASK_ID='calculate_exchange_rate_change' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T21:00:00+00:00'
[2024-08-26T22:00:00.828+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-26T22:00:00.836+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=currency_exchange_dag, task_id=calculate_exchange_rate_change, execution_date=20240826T210000, start_date=20240826T220000, end_date=20240826T220000
[2024-08-26T22:00:00.879+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-26T22:00:00.891+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
