[2024-08-27T14:00:00.976+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T14:00:00.982+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T14:00:00.984+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T14:00:01.010+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T14:00:01.011+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T14:00:01.034+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T13:00:00+00:00 [queued]>
[2024-08-27T14:00:01.041+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T13:00:00+00:00 [queued]>
[2024-08-27T14:00:01.042+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-27T14:00:01.055+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): calculate_exchange_rate_change> on 2024-08-27 13:00:00+00:00
[2024-08-27T14:00:01.060+0000] {standard_task_runner.py:57} INFO - Started process 110 to run task
[2024-08-27T14:00:01.064+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_dag', 'calculate_exchange_rate_change', 'scheduled__2024-08-27T13:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmph8hynpi8']
[2024-08-27T14:00:01.065+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask calculate_exchange_rate_change
[2024-08-27T14:00:01.087+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-27T14:00:01.129+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509
[2024-08-27T14:00:01.130+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=currency_exchange_dag/run_id=scheduled__2024-08-27T13:00:00+00:00/task_id=calculate_exchange_rate_change'
[2024-08-27T14:00:01.134+0000] {task_command.py:410} INFO - Running <TaskInstance: currency_exchange_dag.calculate_exchange_rate_change scheduled__2024-08-27T13:00:00+00:00 [running]> on host d374469d5083
[2024-08-27T14:00:01.150+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-08-27T14:00:01.237+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_dag' AIRFLOW_CTX_TASK_ID='calculate_exchange_rate_change' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T13:00:00+00:00'
[2024-08-27T14:00:01.248+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-27T14:00:01.263+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=currency_exchange_dag, task_id=calculate_exchange_rate_change, execution_date=20240827T130000, start_date=20240827T140001, end_date=20240827T140001
[2024-08-27T14:00:01.319+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-27T14:00:01.334+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
